/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.security.sfd_groupa;

import java.awt.Color;
import javax.swing.JOptionPane;
import org.bouncycastle.util.Arrays;

/**
 *
 * @author rokom
 */
public class CreateAccountFrame extends javax.swing.JFrame {

    private GUIManager guiLiaison;
    private PasswordManager passwordLiaison;
    /**
     * Creates new form CreateAccountFrame
     */
    public CreateAccountFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nameTF = new javax.swing.JTextField();
        nameLBL = new javax.swing.JLabel();
        passwordLBL = new javax.swing.JLabel();
        backBTN = new javax.swing.JButton();
        confirmBTN = new javax.swing.JButton();
        showPasswordCKB = new javax.swing.JCheckBox();
        passwordPF = new javax.swing.JPasswordField();
        strengthPB = new javax.swing.JProgressBar();
        strengthLBL = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        hintTA = new javax.swing.JTextArea();
        progressLBL = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("createAccountFrame"); // NOI18N

        nameTF.setName("nameTF"); // NOI18N
        nameTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTFActionPerformed(evt);
            }
        });

        nameLBL.setText("User Name: ");

        passwordLBL.setText("Password:");

        backBTN.setText("Back");
        backBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBTNActionPerformed(evt);
            }
        });

        confirmBTN.setText("Confirm");
        confirmBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmBTNActionPerformed(evt);
            }
        });

        showPasswordCKB.setText("Show Password");
        showPasswordCKB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showPasswordCKBActionPerformed(evt);
            }
        });

        passwordPF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                passwordPFKeyReleased(evt);
            }
        });

        strengthLBL.setText("Password Strength:");

        hintTA.setEditable(false);
        hintTA.setBackground(new java.awt.Color(224, 224, 224));
        hintTA.setColumns(20);
        hintTA.setLineWrap(true);
        hintTA.setRows(5);
        hintTA.setWrapStyleWord(true);
        hintTA.setAutoscrolls(false);
        jScrollPane1.setViewportView(hintTA);

        progressLBL.setText("...");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(backBTN)
                .addGap(46, 46, 46)
                .addComponent(jScrollPane1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(confirmBTN)
                    .addComponent(progressLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(strengthLBL))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nameLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(passwordLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 99, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(nameTF, javax.swing.GroupLayout.DEFAULT_SIZE, 315, Short.MAX_VALUE)
                    .addComponent(showPasswordCKB)
                    .addComponent(passwordPF)
                    .addComponent(strengthPB, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(56, 56, 56))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameLBL))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordLBL)
                    .addComponent(passwordPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(showPasswordCKB)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(strengthPB, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(strengthLBL))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(progressLBL)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(backBTN)
                            .addComponent(confirmBTN))))
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nameTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameTFActionPerformed

    private void backBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBTNActionPerformed
        // TODO add your handling code here:
        guiLiaison.setCurrentFrame("mainFrame");
        nameTF.setText("");
        passwordPF.setText("");
        progressLBL.setText("???");
        hintTA.setText("Please enter your desired password.");
        strengthPB.setValue(0);
        strengthPB.setForeground(Color.white);
    }//GEN-LAST:event_backBTNActionPerformed

    private void confirmBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmBTNActionPerformed
        // TODO add your handling code here:
        String username = nameTF.getText();
        char[] passwordChars = passwordPF.getPassword();
        String password = new String(passwordChars);
        Arrays.fill(passwordChars, 'a');
        // Validate input
        if (username.isBlank() || username.contains(" ")) {
            JOptionPane.showMessageDialog(rootPane, "Invalid username. Make sure there are no white spaces.");
            return;
        }
        if (password.isBlank() || password.contains(" ")) {
            JOptionPane.showMessageDialog(rootPane, "Invalid password. Make sure there are no white spaces.");
            return;         
        }
        if (passwordLiaison.assertUsernameTaken(username)) {
            JOptionPane.showMessageDialog(rootPane, "User name is already taken!");
            return;
        }
        String hash = passwordLiaison.computePassHash(password);
        if (passwordLiaison.storeCredentialsRemotely(username, hash) && passwordLiaison.calculatePasswordStrength(password) == 4)
            JOptionPane.showMessageDialog(rootPane, "Account has been created!");
        else
            JOptionPane.showMessageDialog(rootPane, "Could not create account.");
        nameTF.setText("");
        passwordPF.setText("");
        guiLiaison.setCurrentFrame("mainFrame");
    }//GEN-LAST:event_confirmBTNActionPerformed

    private void showPasswordCKBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showPasswordCKBActionPerformed
        // TODO add your handling code here:
        if (showPasswordCKB.isSelected())
            passwordPF.setEchoChar((char)0);
        else
            passwordPF.setEchoChar('\u2022');
    }//GEN-LAST:event_showPasswordCKBActionPerformed

    private void passwordPFKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwordPFKeyReleased
        // TODO add your handling code here:
        char[] passwordChars = passwordPF.getPassword();
        String password = new String(passwordChars);
        Arrays.fill(passwordChars, 'a');
        if (password.length() > 0) {
            switch (passwordLiaison.calculatePasswordStrength(password)) {
                case 0:
                    progressLBL.setText("Weak");
                    hintTA.setText("Password should contain at least 8 characters and up to 64 characters.");
                    strengthPB.setValue(33);
                    strengthPB.setForeground(Color.red);
                    break;
                case 1:
                    progressLBL.setText("Moderate");
                    hintTA.setText("Password should not contain repeating characters.");
                    strengthPB.setValue(66);
                    strengthPB.setForeground(Color.yellow);
                    break;
                case 2:
                    progressLBL.setText("Moderate");
                    hintTA.setText("Password should not contain patterns e.g. 'abc'");
                    strengthPB.setValue(66);
                    strengthPB.setForeground(Color.yellow);
                    break;
                case 3:
                    progressLBL.setText("Moderate");
                    hintTA.setText("Password should not be a common/dictionary term.");
                    strengthPB.setValue(66);
                    strengthPB.setForeground(Color.yellow);
                    break;
                case 4:
                    progressLBL.setText("Strong");
                    hintTA.setText("Password is acceptable. Final note: Avoid birthdays.");
                    strengthPB.setValue(100);
                    strengthPB.setForeground(Color.green);
                    break;
            }
        }
        else {
            progressLBL.setText("???");
            hintTA.setText("Please enter your desired password.");
            strengthPB.setValue(0);
            strengthPB.setForeground(Color.white);
        }
    }//GEN-LAST:event_passwordPFKeyReleased

    public void setGUILiaison(GUIManager manager) {
        guiLiaison = manager;
    }
    
    public void setPasswordLiaison(PasswordManager manager) {
        passwordLiaison = manager;
    }
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateAccountFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateAccountFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateAccountFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateAccountFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreateAccountFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBTN;
    private javax.swing.JButton confirmBTN;
    private javax.swing.JTextArea hintTA;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel nameLBL;
    private javax.swing.JTextField nameTF;
    private javax.swing.JLabel passwordLBL;
    private javax.swing.JPasswordField passwordPF;
    private javax.swing.JLabel progressLBL;
    private javax.swing.JCheckBox showPasswordCKB;
    private javax.swing.JLabel strengthLBL;
    private javax.swing.JProgressBar strengthPB;
    // End of variables declaration//GEN-END:variables
}
